mappings:
  - serviceName: "Balkan"
    allowedEnvironments: ["production", "simondev"]
    tokenBase: "BALKAN"
  - serviceName: "TRANSACTIONAL_MESSAGING_-_NEST_APP"
    allowedEnvironments: []
    tokenBase: "NEST"
  - serviceName: "nest"
    allowedEnvironments: ["production", "beta", "development"]
    tokenBase: "NEST"
  - serviceName: "Overseer"
    allowedEnvironments: []
    tokenBase: "OVERSEER"
  - serviceName: "rta-tool"
    allowedEnvironments: ["staging", "dev", "prod"]
    tokenBase: "RTA"
  - # e2e tests
    serviceName: "Venom"
    allowedEnvironments: []
    tokenBase: "VENOM"
