mappings:
  -
    serviceName: "Balkan"
    allowedEnvironments: ["production", "simondev"]
    tokenBase: "BALKAN"
  - 
    serviceName: "TRANSACTIONAL_MESSAGING_-_NEST_APP"
    allowedEnvironments: []
    tokenBase: "NEST"
  -
    serviceName: "Overseer"
    allowedEnvironments: []
    tokenBase: "OVERSEER"
  -
    # e2e tests
    serviceName: "Venom"
    allowedEnvironments: []
    tokenBase: "VENOM"
