mappings:
  -
    serviceName: "Balkan"
    allowedEnvironments: ["production", "simondev"]
    KeyBase: "BALKAN"
  - 
    serviceName: "TRANSACTIONAL_MESSAGING_-_NEST_APP"
    allowedEnvironments: ["production"]
    KeyBase: "NEST"
